name: JAVA CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install -DskipTests --file pom.xml

      - name: Run test
        run: mvn test --file pom.xml || true

      - name: Package all services
        run: mvn package -DskipTests

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: microservice-artifacts
          path: |
            eureka-service/target/*.jar
            gateway-service/target/*.jar
            user-service/target/*.jar
            order-service/target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Eureka image
        run: | 
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/eureka-service:lastest ./EurekaService
          docker push ${{secrets.DOCKERHUB_USERNAME}}/eureka-service:lastest

      - name: Build & Push Gateway image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/gateway-service:lastest ./GatewayService
          docker push ${{secrets.DOCKERHUB_USERNAME}}/gateway-service:lastest

      - name: Build & Push User image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/user-service:lastest ./UserService
          docker push ${{secrets.DOCKERHUB_USERNAME}}/user-service:lastest

      - name: Build & Push Order image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/order-service:lastest ./OrderService
          docker push ${{secrets.DOCKERHUB_USERNAME}}/order-service:lastest